export default {
  SET_CURRENT_GENRE: `SET_CURRENT_GENRE`,
  SET_FILTRED_FILMS_BY_GENRE: `SET_FILTRED_FILMS_BY_GENRE`,
  INCREASE_DISPLAYED_FILMS_COUNT: `INCREASE_DISPLAYED_FILMS_COUNT`,
  RESET_DISPLAYED_FILMS_COUNT: `RESET_DISPLAYED_FILMS_COUNT`
};

