export default {
  GET_MOVIE: `GET_MOVIE`,
  GET_MOVIES: `GET_MOVIES`,
  SET_CURRENT_GENRE: `SET_CURRENT_GENRE`,
  SET_CURRENT_SMALL_MOVIE: `SET_CURRENT_SMALL_MOVIE`,
  SET_FILTRED_FILMS_BY_GENRE: `SET_FILTRED_FILMS_BY_GENRE`,
  INCREASE_DISPLAYED_FILMS_COUNT: `INCREASE_DISPLAYED_FILMS_COUNT`,
  RESET_DISPLAYED_FILMS_COUNT: `RESET_DISPLAYED_FILMS_COUNT`,
  CHANGE_PLAYING_MOVIE: `CHANGE_PLAYING_MOVIE`,
  RENDER_SIGN_IN_PAGE: `RENDER_SIGN_IN_PAGE`,
  RENDER_MAIN_PAGE: `RENDER_MAIN_PAGE`
};

